services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      
      - WEBHOOK_URL=https://n8n.${DOMAIN_NAME}
      - N8N_EDITOR_BASE_URL=https://n8n.${DOMAIN_NAME}
      
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DATABASE_DATABASE}
      - DB_POSTGRESDB_USER=${N8N_DATABASE_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DATABASE_PASSWORD}
      
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_FOLDER=/home/node/.n8n
      
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_MAX_AGE=168
      - EXECUTIONS_DATA_PRUNE=true
      
      - N8N_WORKERS_ENABLED=true
      - N8N_WORKERS_COUNT=2
      
      - GENERIC_TIMEZONE=Europe/Warsaw
      - TZ=Europe/Warsaw
      
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - n8n
      - homelab
    depends_on:
      n8n-db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
      - "traefik.http.routers.n8n.service=n8n"
      - "traefik.http.routers.n8n.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  n8n-db:
    image: postgres:17-alpine
    container_name: n8n-db
    environment:
      - POSTGRES_PASSWORD=${N8N_DATABASE_PASSWORD}
      - POSTGRES_USER=${N8N_DATABASE_USER}
      - POSTGRES_DB=${N8N_DATABASE_DATABASE}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - n8n
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 2s
      start_period: 30s

networks:
  n8n:
    name: n8n
  homelab:
    name: homelab
    external: true
