services:
  k6:
    build: .
    container_name: k6
    env_file:
      - .env
    networks: 
      - grafana-monitoring
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    working_dir: /scripts
    environment:
      - K6_BROWSER_ENABLED=true
      - K6_INFLUXDB_ORGANIZATION=${K6_INFLUXDB_ORGANIZATION}
      - K6_INFLUXDB_BUCKET=${K6_INFLUXDB_BUCKET}
      - K6_INFLUXDB_TOKEN=${K6_INFLUXDB_TOKEN}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "65534:65534"
    security_opt:
      - no-new-privileges:true
    networks:
      - grafana-monitoring
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=90d'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=cloudflare"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "65534:65534"
    security_opt:
      - no-new-privileges:true
    networks:
      - homelab
      - grafana-monitoring
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PSWD}
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    user: telegraf:${DOCKER_GID} #you need to find the GID of Docker if not added to Sudo group
    security_opt:
      - no-new-privileges:true
    networks:
      - grafana-monitoring
    volumes:
      - './telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      - '/:/hostfs:ro' 
      - '/var/run/docker.sock:/var/run/docker.sock' 
      - ./mibs:/usr/share/snmp/mibs' 
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs

      - INFLUX_TOKEN_DOCKER=${INFLUX_TOKEN_DOCKER}
      - INFLUX_TOKEN_PROXMOX=${INFLUX_TOKEN_PROXMOX}

      - INFLUX_DOCKER_BUCKET=${INFLUX_DOCKER_BUCKET}
      - INFLUX_PROXMOX_BUCKET=${INFLUX_PROXMOX_BUCKET}
      - INFLUX_ORG=${INFLUX_ORG}

      - PVE_HOST=${PVE_HOST}
      - PVE_USER=${PVE_USER}
      - PVE_TOKEN_NAME=${PVE_TOKEN_NAME}
      - PVE_TOKEN_VALUE=${PVE_TOKEN_VALUE}

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    user: "10001:10001"
    security_opt:
      - no-new-privileges:true
    networks:
      - grafana-monitoring
      - homelab
    volumes:
      - ./loki_config/config.yaml:/etc/loki/config.yaml:ro
      - ./loki_data:/loki:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.rule=Host(`loki.${DOMAIN_NAME}`)"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=cloudflare"
      - "traefik.http.routers.loki.service=loki"
      - "traefik.http.routers.loki.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: alloy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - grafana-monitoring
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.rule=Host(`alloy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.alloy.tls=true"
      - "traefik.http.routers.alloy.tls.certresolver=cloudflare"
      - "traefik.http.routers.alloy.service=alloy"
      - "traefik.http.routers.alloy.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"

  influxdb:
      container_name: influxdb
      image: influxdb:latest
      restart: unless-stopped
      networks:
        - homelab
        - grafana-monitoring
      volumes:
        - ./influxdb:/var/lib/influxdb2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.influxdb.entrypoints=websecure"
        - "traefik.http.routers.influxdb.rule=Host(`influx.${DOMAIN_NAME}`)"
        - "traefik.http.routers.influxdb.tls=true"
        - "traefik.http.routers.influxdb.tls.certresolver=cloudflare"
        - "traefik.http.routers.influxdb.service=influxdb"
        - "traefik.http.routers.influxdb.middlewares=local-only@file"
        - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

volumes:
  alloy_data:
    driver: local

networks:
  grafana-monitoring:
    name: grafana-monitoring
  homelab:
    name: homelab
    external: true
